name: Autobump

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-15
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v7
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          tap: ulrikpedersen/epics
          push: true
          no-fork: true
          livecheck: true
